"""Design tokens for md.comp.suggestion-chip."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

container_height = 32
container_shape = 'md.sys.shape.corner.small'
container_surface_tint_layer_color = 'md.sys.color.surface-tint'
disabled_label_text_color = 'md.sys.color.on-surface'
disabled_label_text_opacity = 0.38
dragged_container_elevation = 'md.sys.elevation.level4'
dragged_label_text_color = 'md.sys.color.on-surface-variant'
dragged_state_layer_color = 'md.sys.color.on-surface-variant'
dragged_state_layer_opacity = 'md.sys.state.dragged.state-layer-opacity'
elevated_container_color = 'md.sys.color.surface-container-low'
elevated_container_elevation = 'md.sys.elevation.level1'
elevated_container_shadow_color = 'md.sys.color.shadow'
elevated_disabled_container_color = 'md.sys.color.on-surface'
elevated_disabled_container_elevation = 'md.sys.elevation.level0'
elevated_disabled_container_opacity = 0.12
elevated_focus_container_elevation = 'md.sys.elevation.level1'
elevated_hover_container_elevation = 'md.sys.elevation.level2'
elevated_pressed_container_elevation = 'md.sys.elevation.level1'
flat_container_elevation = 'md.sys.elevation.level0'
flat_disabled_outline_color = 'md.sys.color.on-surface'
flat_disabled_outline_opacity = 0.12
flat_focus_outline_color = 'md.sys.color.on-surface-variant'
flat_outline_color = 'md.sys.color.outline-variant'
flat_outline_width = 1
focus_indicator_color = 'md.sys.color.secondary'
focus_indicator_outline_offset = 'md.sys.state.focus-indicator.outer-offset'
focus_indicator_thickness = 'md.sys.state.focus-indicator.thickness'
focus_label_text_color = 'md.sys.color.on-surface-variant'
focus_state_layer_color = 'md.sys.color.on-surface-variant'
focus_state_layer_opacity = 'md.sys.state.focus.state-layer-opacity'
hover_label_text_color = 'md.sys.color.on-surface-variant'
hover_state_layer_color = 'md.sys.color.on-surface-variant'
hover_state_layer_opacity = 'md.sys.state.hover.state-layer-opacity'
label_text_color = 'md.sys.color.on-surface-variant'
label_text_font = 'md.sys.typescale.label-large.font'
label_text_line_height = 'md.sys.typescale.label-large.line-height'
label_text_size = 'md.sys.typescale.label-large.size'
label_text_tracking = 'md.sys.typescale.label-large.tracking'
label_text_weight = 'md.sys.typescale.label-large.weight'
pressed_label_text_color = 'md.sys.color.on-surface-variant'
pressed_state_layer_color = 'md.sys.color.on-surface-variant'
pressed_state_layer_opacity = 'md.sys.state.pressed.state-layer-opacity'
with_leading_icon_disabled_leading_icon_color = 'md.sys.color.on-surface'
with_leading_icon_disabled_leading_icon_opacity = 0.38
with_leading_icon_dragged_leading_icon_color = 'md.sys.color.primary'
with_leading_icon_focus_leading_icon_color = 'md.sys.color.primary'
with_leading_icon_hover_leading_icon_color = 'md.sys.color.primary'
with_leading_icon_leading_icon_color = 'md.sys.color.primary'
with_leading_icon_leading_icon_size = 18
with_leading_icon_pressed_leading_icon_color = 'md.sys.color.primary'
