"""Design tokens for md.comp.navigation-bar."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

active_indicator_color = 'md.sys.color.secondary-container'
active_indicator_height = 32
active_indicator_shape = 'md.sys.shape.corner.full'
active_indicator_width = 64
active_focus_icon_color = 'md.sys.color.on-secondary-container'
active_focus_label_text_color = 'md.sys.color.on-surface'
active_focus_state_layer_color = 'md.sys.color.on-surface'
active_hover_icon_color = 'md.sys.color.on-secondary-container'
active_hover_label_text_color = 'md.sys.color.on-surface'
active_hover_state_layer_color = 'md.sys.color.on-surface'
active_icon_color = 'md.sys.color.on-secondary-container'
active_label_text_color = 'md.sys.color.on-surface'
active_label_text_weight = 'md.sys.typescale.label-medium.weight.prominent'
active_pressed_icon_color = 'md.sys.color.on-secondary-container'
active_pressed_label_text_color = 'md.sys.color.on-surface'
active_pressed_state_layer_color = 'md.sys.color.on-surface'
badge_color = 'md.sys.color.error'
badge_shape = 'SHAPE_FAMILY_ROUNDED_CORNERS'
badge_size = 6
container_color = 'md.sys.color.surface-container'
container_elevation = 'md.sys.elevation.level2'
container_height = 80
container_shadow_color = 'md.sys.color.shadow'
container_shape = 'md.sys.shape.corner.none'
container_surface_tint_layer_color = 'md.sys.color.surface-tint'
focus_indicator_color = 'md.sys.color.secondary'
focus_indicator_outline_offset = 'md.sys.state.focus-indicator.inner-offset'
focus_indicator_thickness = 'md.sys.state.focus-indicator.thickness'
focus_state_layer_opacity = 'md.sys.state.focus.state-layer-opacity'
hover_state_layer_opacity = 'md.sys.state.hover.state-layer-opacity'
icon_size = 24
inactive_focus_icon_color = 'md.sys.color.on-surface'
inactive_focus_label_text_color = 'md.sys.color.on-surface'
inactive_focus_state_layer_color = 'md.sys.color.on-surface'
inactive_hover_icon_color = 'md.sys.color.on-surface'
inactive_hover_label_text_color = 'md.sys.color.on-surface'
inactive_hover_state_layer_color = 'md.sys.color.on-surface'
inactive_icon_color = 'md.sys.color.on-surface-variant'
inactive_label_text_color = 'md.sys.color.on-surface-variant'
inactive_pressed_icon_color = 'md.sys.color.on-surface'
inactive_pressed_label_text_color = 'md.sys.color.on-surface'
inactive_pressed_state_layer_color = 'md.sys.color.on-surface'
label_text_font = 'md.sys.typescale.label-medium.font'
label_text_line_height = 'md.sys.typescale.label-medium.line-height'
label_text_size = 'md.sys.typescale.label-medium.size'
label_text_tracking = 'md.sys.typescale.label-medium.tracking'
label_text_weight = 'md.sys.typescale.label-medium.weight'
large_badge_color = 'md.sys.color.error'
large_badge_shape = 'SHAPE_FAMILY_ROUNDED_CORNERS'
large_badge_size = 16
pressed_state_layer_opacity = 'md.sys.state.pressed.state-layer-opacity'
