# Generated by _token_converter.py
# Do not edit this file directly.
# Instead, run the script to regenerate it.
active_indicator_color = 'md.sys.color.primary'
active_indicator_shape = 'md.sys.shape.corner.none'
active_indicator_width = '4 DIPS'
four_color_active_indicator_four_color = 'md.sys.color.tertiary-container'
four_color_active_indicator_one_color = 'md.sys.color.primary'
four_color_active_indicator_three_color = 'md.sys.color.tertiary'
four_color_active_indicator_two_color = 'md.sys.color.primary-container'
size = '48 DIPS'
