"""Design tokens for md.comp.plain-tooltip."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

container_color = 'md.sys.color.inverse-surface'
container_shape = 'md.sys.shape.corner.extra-small'
supporting_text_color = 'md.sys.color.inverse-on-surface'
supporting_text_font = 'md.sys.typescale.body-small.font'
supporting_text_line_height = 'md.sys.typescale.body-small.line-height'
supporting_text_size = 'md.sys.typescale.body-small.size'
supporting_text_tracking = 'md.sys.typescale.body-small.tracking'
supporting_text_weight = 'md.sys.typescale.body-small.weight'
