"""Design tokens for md.comp.search-view."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

container_color = 'md.sys.color.surface-container-high'
container_elevation = 'md.sys.elevation.level3'
container_surface_tint_layer_color = 'md.sys.color.surface-tint'
divider_color = 'md.sys.color.outline'
docked_container_shape = 'md.sys.shape.corner.extra-large'
docked_header_container_height = 56
full_screen_container_shape = 'md.sys.shape.corner.none'
full_screen_header_container_height = 72
header_input_text_color = 'md.sys.color.on-surface'
header_input_text_font = 'md.sys.typescale.body-large.font'
header_input_text_line_height = 'md.sys.typescale.body-large.line-height'
header_input_text_size = 'md.sys.typescale.body-large.size'
header_input_text_tracking = 'md.sys.typescale.body-large.tracking'
header_input_text_weight = 'md.sys.typescale.body-large.weight'
header_leading_icon_color = 'md.sys.color.on-surface'
header_supporting_text_color = 'md.sys.color.on-surface-variant'
header_supporting_text_font = 'md.sys.typescale.body-large.font'
header_supporting_text_line_height = 'md.sys.typescale.body-large.line-height'
header_supporting_text_size = 'md.sys.typescale.body-large.size'
header_supporting_text_tracking = 'md.sys.typescale.body-large.tracking'
header_supporting_text_weight = 'md.sys.typescale.body-large.weight'
header_trailing_icon_color = 'md.sys.color.on-surface-variant'
