"""Design tokens for md.comp.sheet."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

bottom_docked_container_color = 'md.sys.color.surface-container-low'
bottom_docked_container_shape = 'md.sys.shape.corner.extra-large.top'
bottom_docked_container_surface_tint_layer_color = 'md.sys.color.surface-tint'
bottom_docked_drag_handle_color = 'md.sys.color.on-surface-variant'
bottom_docked_drag_handle_height = 4
bottom_docked_drag_handle_opacity = 0.4
bottom_docked_drag_handle_width = 32
bottom_docked_minimized_container_shape = 'md.sys.shape.corner.none'
bottom_docked_modal_container_elevation = 'md.sys.elevation.level1'
bottom_docked_standard_container_elevation = 'md.sys.elevation.level1'
bottom_focus_indicator_color = 'md.sys.color.secondary'
bottom_focus_indicator_outline_offset = 'md.sys.state.focus-indicator.outer-offset'
bottom_focus_indicator_thickness = 'md.sys.state.focus-indicator.thickness'
side_detached_container_shape = 'md.sys.shape.corner.large'
side_docked_action_focus_label_text_color = 'md.sys.color.primary'
side_docked_action_focus_state_layer_color = 'md.sys.color.primary'
side_docked_action_focus_state_layer_opacity = 'md.sys.state.focus.state-layer-opacity'
side_docked_action_hover_label_text_color = 'md.sys.color.primary'
side_docked_action_hover_state_layer_color = 'md.sys.color.primary'
side_docked_action_hover_state_layer_opacity = 'md.sys.state.hover.state-layer-opacity'
side_docked_action_pressed_label_text_color = 'md.sys.color.primary'
side_docked_action_pressed_state_layer_color = 'md.sys.color.primary'
side_docked_action_pressed_state_layer_opacity = 'md.sys.state.pressed.state-layer-opacity'
side_docked_container_color = 'md.sys.color.surface'
side_docked_container_height = 1.0
side_docked_container_shape = 'md.sys.shape.corner.none'
side_docked_container_surface_tint_layer_color = 'md.sys.color.surface-tint'
side_docked_container_width = 256
side_docked_divider_color = 'md.sys.color.outline'
side_docked_focus_indicator_color = 'md.sys.color.secondary'
side_docked_focus_indicator_outline_offset = 'md.sys.state.focus-indicator.outer-offset'
side_docked_focus_indicator_thickness = 'md.sys.state.focus-indicator.thickness'
side_docked_headline_color = 'md.sys.color.on-surface-variant'
side_docked_headline_font = 'md.sys.typescale.title-large.font'
side_docked_headline_line_height = 'md.sys.typescale.title-large.line-height'
side_docked_headline_size = 'md.sys.typescale.title-large.size'
side_docked_headline_tracking = 'md.sys.typescale.title-large.tracking'
side_docked_headline_weight = 'md.sys.typescale.title-large.weight'
side_docked_modal_container_color = 'md.sys.color.surface-container-low'
side_docked_modal_container_elevation = 'md.sys.elevation.level1'
side_docked_modal_container_shape = 'md.sys.shape.corner.large.start'
side_docked_standard_container_color = 'md.sys.color.surface'
side_docked_standard_container_elevation = 'md.sys.elevation.level0'
