"""Design tokens for md.comp.secondary-navigation-tab."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

active_indicator_color = 'md.sys.color.primary'
active_indicator_height = 2
active_label_text_color = 'md.sys.color.on-surface'
container_color = 'md.sys.color.surface'
container_elevation = 'md.sys.elevation.level0'
container_height = 48
container_shadow_color = 'md.sys.color.shadow'
container_shape = 'md.sys.shape.corner.none'
divider_color = 'md.sys.color.surface-variant'
divider_height = 1
focus_indicator_color = 'md.sys.color.secondary'
focus_indicator_outline_offset = 'md.sys.state.focus-indicator.inner-offset'
focus_indicator_thickness = 'md.sys.state.focus-indicator.thickness'
focus_label_text_color = 'md.sys.color.on-surface'
focus_state_layer_color = 'md.sys.color.on-surface'
focus_state_layer_opacity = 'md.sys.state.focus.state-layer-opacity'
hover_label_text_color = 'md.sys.color.on-surface'
hover_state_layer_color = 'md.sys.color.on-surface'
hover_state_layer_opacity = 'md.sys.state.hover.state-layer-opacity'
inactive_label_text_color = 'md.sys.color.on-surface-variant'
label_text_font = 'md.sys.typescale.title-small.font'
label_text_line_height = 'md.sys.typescale.title-small.line-height'
label_text_size = 'md.sys.typescale.title-small.size'
label_text_tracking = 'md.sys.typescale.title-small.tracking'
label_text_weight = 'md.sys.typescale.title-small.weight'
pressed_label_text_color = 'md.sys.color.on-surface'
pressed_state_layer_color = 'md.sys.color.on-surface'
pressed_state_layer_opacity = 'md.sys.state.pressed.state-layer-opacity'
with_icon_active_icon_color = 'md.sys.color.on-surface'
with_icon_focus_icon_color = 'md.sys.color.on-surface'
with_icon_hover_icon_color = 'md.sys.color.on-surface'
with_icon_icon_size = 24
with_icon_inactive_icon_color = 'md.sys.color.on-surface-variant'
with_icon_pressed_icon_color = 'md.sys.color.on-surface'
