"""Design tokens for md.comp.snackbar."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

action_focus_label_text_color = 'md.sys.color.inverse-primary'
action_focus_state_layer_color = 'md.sys.color.inverse-primary'
action_focus_state_layer_opacity = 'md.sys.state.focus.state-layer-opacity'
action_hover_label_text_color = 'md.sys.color.inverse-primary'
action_hover_state_layer_color = 'md.sys.color.inverse-primary'
action_hover_state_layer_opacity = 'md.sys.state.hover.state-layer-opacity'
action_label_text_color = 'md.sys.color.inverse-primary'
action_label_text_font = 'md.sys.typescale.label-large.font'
action_label_text_line_height = 'md.sys.typescale.label-large.line-height'
action_label_text_size = 'md.sys.typescale.label-large.size'
action_label_text_tracking = 'md.sys.typescale.label-large.tracking'
action_label_text_weight = 'md.sys.typescale.label-large.weight'
action_pressed_label_text_color = 'md.sys.color.inverse-primary'
action_pressed_state_layer_color = 'md.sys.color.inverse-primary'
action_pressed_state_layer_opacity = 'md.sys.state.pressed.state-layer-opacity'
container_color = 'md.sys.color.inverse-surface'
container_elevation = 'md.sys.elevation.level3'
container_shadow_color = 'md.sys.color.shadow'
container_shape = 'md.sys.shape.corner.extra-small'
icon_color = 'md.sys.color.inverse-on-surface'
icon_focus_icon_color = 'md.sys.color.inverse-on-surface'
icon_focus_state_layer_color = 'md.sys.color.inverse-on-surface'
icon_focus_state_layer_opacity = 'md.sys.state.focus.state-layer-opacity'
icon_hover_icon_color = 'md.sys.color.inverse-on-surface'
icon_hover_state_layer_color = 'md.sys.color.inverse-on-surface'
icon_hover_state_layer_opacity = 'md.sys.state.hover.state-layer-opacity'
icon_pressed_icon_color = 'md.sys.color.inverse-on-surface'
icon_pressed_state_layer_color = 'md.sys.color.inverse-on-surface'
icon_pressed_state_layer_opacity = 'md.sys.state.pressed.state-layer-opacity'
icon_size = 24
supporting_text_color = 'md.sys.color.inverse-on-surface'
supporting_text_font = 'md.sys.typescale.body-medium.font'
supporting_text_line_height = 'md.sys.typescale.body-medium.line-height'
supporting_text_size = 'md.sys.typescale.body-medium.size'
supporting_text_tracking = 'md.sys.typescale.body-medium.tracking'
supporting_text_weight = 'md.sys.typescale.body-medium.weight'
with_single_line_container_height = 48
with_two_lines_container_height = 68
