# Generated by _token_converter.py
# Do not edit this file directly.
# Instead, run the script to regenerate it.
disabled_selected_icon_color = 'md.sys.color.on-surface'
disabled_selected_icon_opacity = 0.38
disabled_unselected_icon_color = 'md.sys.color.on-surface'
disabled_unselected_icon_opacity = 0.38
icon_size = '20 DIPS'
selected_focus_icon_color = 'md.sys.color.primary'
selected_focus_state_layer_color = 'md.sys.color.primary'
selected_focus_state_layer_opacity = 'md.sys.state.focus.state-layer-opacity'
selected_hover_icon_color = 'md.sys.color.primary'
selected_hover_state_layer_color = 'md.sys.color.primary'
selected_hover_state_layer_opacity = 'md.sys.state.hover.state-layer-opacity'
selected_icon_color = 'md.sys.color.primary'
selected_pressed_icon_color = 'md.sys.color.primary'
selected_pressed_state_layer_color = 'md.sys.color.on-surface'
selected_pressed_state_layer_opacity = 'md.sys.state.pressed.state-layer-opacity'
state_layer_size = '40 DIPS'
unselected_focus_icon_color = 'md.sys.color.on-surface'
unselected_focus_state_layer_color = 'md.sys.color.on-surface'
unselected_focus_state_layer_opacity = 'md.sys.state.focus.state-layer-opacity'
unselected_hover_icon_color = 'md.sys.color.on-surface'
unselected_hover_state_layer_color = 'md.sys.color.on-surface'
unselected_hover_state_layer_opacity = 'md.sys.state.hover.state-layer-opacity'
unselected_icon_color = 'md.sys.color.on-surface-variant'
unselected_pressed_icon_color = 'md.sys.color.on-surface'
unselected_pressed_state_layer_color = 'md.sys.color.primary'
unselected_pressed_state_layer_opacity = 'md.sys.state.pressed.state-layer-opacity'
