"""Design tokens for md.comp.text-button."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

container_elevation = 'md.sys.elevation.level0'
container_height = '40 DIPS'
container_shape = 'md.sys.shape.corner.full'
disabled_label_text_color = 'md.sys.color.on-surface'
disabled_label_text_opacity = 0.38
focus_indicator_color = 'md.sys.color.secondary'
focus_indicator_outline_offset = 'md.sys.state.focus-indicator.outer-offset'
focus_indicator_thickness = 'md.sys.state.focus-indicator.thickness'
focus_label_text_color = 'md.sys.color.primary'
focus_state_layer_color = 'md.sys.color.primary'
focus_state_layer_opacity = 'md.sys.state.focus.state-layer-opacity'
hover_label_text_color = 'md.sys.color.primary'
hover_state_layer_color = 'md.sys.color.primary'
hover_state_layer_opacity = 'md.sys.state.hover.state-layer-opacity'
label_text_color = 'md.sys.color.primary'
label_text_font = 'md.sys.typescale.label-large.font'
label_text_line_height = 'md.sys.typescale.label-large.line-height'
label_text_size = 'md.sys.typescale.label-large.size'
label_text_tracking = 'md.sys.typescale.label-large.tracking'
label_text_weight = 'md.sys.typescale.label-large.weight'
pressed_label_text_color = 'md.sys.color.primary'
pressed_state_layer_color = 'md.sys.color.primary'
pressed_state_layer_opacity = 'md.sys.state.pressed.state-layer-opacity'
with_icon_disabled_icon_color = 'md.sys.color.on-surface'
with_icon_disabled_icon_opacity = 0.38
with_icon_focus_icon_color = 'md.sys.color.primary'
with_icon_hover_icon_color = 'md.sys.color.primary'
with_icon_icon_color = 'md.sys.color.primary'
with_icon_icon_size = '18 DIPS'
with_icon_pressed_icon_color = 'md.sys.color.primary'
