"""Design tokens for md.comp.badge."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

color = 'md.sys.color.error'
large_color = 'md.sys.color.error'
large_label_text_color = 'md.sys.color.on-error'
large_label_text_font = 'md.sys.typescale.label-small.font'
large_label_text_line_height = 'md.sys.typescale.label-small.line-height'
large_label_text_size = 'md.sys.typescale.label-small.size'
large_label_text_tracking = 'md.sys.typescale.label-small.tracking'
large_label_text_weight = 'md.sys.typescale.label-small.weight'
large_shape = 'md.sys.shape.corner.full'
large_size = 16
shape = 'md.sys.shape.corner.full'
size = 6
