"""Design tokens for md.comp.icon-button."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

disabled_icon_color = 'md.sys.color.on-surface'
disabled_icon_opacity = 0.38
focus_indicator_color = 'md.sys.color.secondary'
focus_indicator_outline_offset = 'md.sys.state.focus-indicator.outer-offset'
focus_indicator_thickness = 'md.sys.state.focus-indicator.thickness'
icon_size = 24
selected_focus_icon_color = 'md.sys.color.primary'
selected_focus_state_layer_color = 'md.sys.color.primary'
selected_focus_state_layer_opacity = 'md.sys.state.focus.state-layer-opacity'
selected_hover_icon_color = 'md.sys.color.primary'
selected_hover_state_layer_color = 'md.sys.color.primary'
selected_hover_state_layer_opacity = 'md.sys.state.hover.state-layer-opacity'
selected_icon_color = 'md.sys.color.primary'
selected_pressed_icon_color = 'md.sys.color.primary'
selected_pressed_state_layer_color = 'md.sys.color.primary'
selected_pressed_state_layer_opacity = 'md.sys.state.pressed.state-layer-opacity'
state_layer_height = 40
state_layer_shape = 'md.sys.shape.corner.full'
state_layer_size = 40
state_layer_width = 40
unselected_focus_icon_color = 'md.sys.color.on-surface-variant'
unselected_focus_state_layer_color = 'md.sys.color.on-surface-variant'
unselected_focus_state_layer_opacity = 'md.sys.state.focus.state-layer-opacity'
unselected_hover_icon_color = 'md.sys.color.on-surface-variant'
unselected_hover_state_layer_color = 'md.sys.color.on-surface-variant'
unselected_hover_state_layer_opacity = 'md.sys.state.hover.state-layer-opacity'
unselected_icon_color = 'md.sys.color.on-surface-variant'
unselected_pressed_icon_color = 'md.sys.color.on-surface-variant'
unselected_pressed_state_layer_color = 'md.sys.color.on-surface-variant'
unselected_pressed_state_layer_opacity = 'md.sys.state.pressed.state-layer-opacity'
