"""Design tokens for md.comp.outlined-segmented-button."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

container_height = 40
disabled_icon_color = 'md.sys.color.on-surface'
disabled_icon_opacity = 0.38
disabled_label_text_color = 'md.sys.color.on-surface'
disabled_label_text_opacity = 0.38
disabled_outline_color = 'md.sys.color.on-surface'
disabled_outline_opacity = 0.12
focus_indicator_color = 'md.sys.color.secondary'
focus_indicator_outline_offset = 'md.sys.state.focus-indicator.outer-offset'
focus_indicator_thickness = 'md.sys.state.focus-indicator.thickness'
focus_state_layer_opacity = 'md.sys.state.focus.state-layer-opacity'
hover_state_layer_opacity = 'md.sys.state.hover.state-layer-opacity'
label_text_font = 'md.sys.typescale.label-large.font'
label_text_line_height = 'md.sys.typescale.label-large.line-height'
label_text_size = 'md.sys.typescale.label-large.size'
label_text_tracking = 'md.sys.typescale.label-large.tracking'
label_text_weight = 'md.sys.typescale.label-large.weight'
outline_color = 'md.sys.color.outline'
outline_width = 1
pressed_state_layer_opacity = 'md.sys.state.focus.state-layer-opacity'
selected_container_color = 'md.sys.color.secondary-container'
selected_focus_icon_color = 'md.sys.color.on-secondary-container'
selected_focus_label_text_color = 'md.sys.color.on-secondary-container'
selected_focus_state_layer_color = 'md.sys.color.on-secondary-container'
selected_hover_icon_color = 'md.sys.color.on-secondary-container'
selected_hover_label_text_color = 'md.sys.color.on-secondary-container'
selected_hover_state_layer_color = 'md.sys.color.on-secondary-container'
selected_label_text_color = 'md.sys.color.on-secondary-container'
selected_pressed_icon_color = 'md.sys.color.on-secondary-container'
selected_pressed_label_text_color = 'md.sys.color.on-secondary-container'
selected_pressed_state_layer_color = 'md.sys.color.on-secondary-container'
selected_with_icon_icon_color = 'md.sys.color.on-secondary-container'
shape = 'md.sys.shape.corner.full'
unselected_focus_icon_color = 'md.sys.color.on-surface'
unselected_focus_label_text_color = 'md.sys.color.on-surface'
unselected_focus_state_layer_color = 'md.sys.color.on-surface'
unselected_hover_icon_color = 'md.sys.color.on-surface'
unselected_hover_label_text_color = 'md.sys.color.on-surface'
unselected_hover_state_layer_color = 'md.sys.color.on-surface'
unselected_label_text_color = 'md.sys.color.on-surface'
unselected_pressed_icon_color = 'md.sys.color.on-surface'
unselected_pressed_label_text_color = 'md.sys.color.on-surface'
unselected_pressed_state_layer_color = 'md.sys.color.on-surface'
unselected_with_icon_icon_color = 'md.sys.color.on-surface'
with_icon_icon_size = 18
