"""Design tokens for md.comp.outlined-icon-button."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

container_height = 40
container_shape = 'md.sys.shape.corner.full'
container_size = 40
container_width = 40
disabled_icon_color = 'md.sys.color.on-surface'
disabled_icon_opacity = 0.38
disabled_outline_color = 'md.sys.color.on-surface'
disabled_outline_opacity = 0.12
disabled_selected_container_color = 'md.sys.color.on-surface'
disabled_selected_container_opacity = 0.12
disabled_unselected_outline_color = 'md.sys.color.on-surface'
disabled_unselected_outline_opacity = 0.12
focus_indicator_color = 'md.sys.color.secondary'
focus_indicator_outline_offset = 'md.sys.state.focus-indicator.outer-offset'
focus_indicator_thickness = 'md.sys.state.focus-indicator.thickness'
focus_state_layer_opacity = 'md.sys.state.hover.state-layer-opacity'
hover_state_layer_opacity = 'md.sys.state.hover.state-layer-opacity'
icon_size = 24
pressed_state_layer_opacity = 'md.sys.state.pressed.state-layer-opacity'
selected_container_color = 'md.sys.color.inverse-surface'
selected_focus_icon_color = 'md.sys.color.inverse-on-surface'
selected_focus_state_layer_color = 'md.sys.color.inverse-on-surface'
selected_hover_icon_color = 'md.sys.color.inverse-on-surface'
selected_hover_state_layer_color = 'md.sys.color.inverse-on-surface'
selected_icon_color = 'md.sys.color.inverse-on-surface'
selected_pressed_icon_color = 'md.sys.color.inverse-on-surface'
selected_pressed_state_layer_color = 'md.sys.color.inverse-on-surface'
unselected_focus_icon_color = 'md.sys.color.on-surface-variant'
unselected_focus_state_layer_color = 'md.sys.color.on-surface-variant'
unselected_hover_icon_color = 'md.sys.color.on-surface-variant'
unselected_hover_state_layer_color = 'md.sys.color.on-surface-variant'
unselected_icon_color = 'md.sys.color.on-surface-variant'
unselected_outline_color = 'md.sys.color.outline'
unselected_outline_width = 1
unselected_pressed_icon_color = 'md.sys.color.on-surface'
unselected_pressed_state_layer_color = 'md.sys.color.on-surface'
