"""Design tokens for md.comp.filled-card."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

container_color = 'md.sys.color.surface-container-highest'
container_elevation = 'md.sys.elevation.level0'
container_shadow_color = 'md.sys.color.shadow'
container_shape = 'md.sys.shape.corner.medium'
container_surface_tint_layer_color = 'md.sys.color.surface-tint'
disabled_container_color = 'md.sys.color.surface-variant'
disabled_container_elevation = 'md.sys.elevation.level0'
disabled_container_opacity = 0.38
dragged_container_elevation = 'md.sys.elevation.level3'
dragged_state_layer_color = 'md.sys.color.on-surface'
dragged_state_layer_opacity = 'md.sys.state.dragged.state-layer-opacity'
focus_container_elevation = 'md.sys.elevation.level0'
focus_indicator_color = 'md.sys.color.secondary'
focus_indicator_outline_offset = 'md.sys.state.focus-indicator.outer-offset'
focus_indicator_thickness = 'md.sys.state.focus-indicator.thickness'
focus_state_layer_color = 'md.sys.color.on-surface'
focus_state_layer_opacity = 'md.sys.state.focus.state-layer-opacity'
hover_container_elevation = 'md.sys.elevation.level1'
hover_state_layer_color = 'md.sys.color.on-surface'
hover_state_layer_opacity = 'md.sys.state.hover.state-layer-opacity'
icon_color = 'md.sys.color.primary'
icon_size = '24 DIPS'
pressed_container_elevation = 'md.sys.elevation.level0'
pressed_state_layer_color = 'md.sys.color.on-surface'
pressed_state_layer_opacity = 'md.sys.state.pressed.state-layer-opacity'
