# Generated by _token_converter.py
# Do not edit this file directly.
# Instead, run the script to regenerate it.
active_indicator_track_space = '4 DIPS'
active_indicator_color = 'md.sys.color.primary'
active_indicator_shape = 'md.sys.shape.corner.full'
active_indicator_thickness = '4 DIPS'
stop_indicator_color = 'md.sys.color.primary'
stop_indicator_shape = '4 DIPS'
stop_indicator_size = '4 DIPS'
track_color = 'md.sys.color.secondary-container'
track_shape = 'md.sys.shape.corner.full'
track_thickness = '4 DIPS'
