"""Design tokens for md.comp.carousel-item."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

container_color = 'md.sys.color.surface'
container_elevation = 'md.sys.elevation.level0'
container_shadow_color = 'md.sys.color.shadow'
container_shape = 'md.sys.shape.corner.extra-large'
container_surface_tint_layer_color = 'md.sys.color.surface-tint'
disabled_container_color = 'md.sys.color.surface'
disabled_container_elevation = 'md.sys.elevation.level0'
disabled_container_opacity = 0.38
focus_container_elevation = 'md.sys.elevation.level0'
focus_indicator_color = 'md.sys.color.secondary'
focus_indicator_outline_offset = 'md.sys.state.focus-indicator.outer-offset'
focus_indicator_thickness = 'md.sys.state.focus-indicator.thickness'
focus_state_layer_color = 'md.sys.color.on-surface'
focus_state_layer_opacity = 'md.sys.state.focus.state-layer-opacity'
hover_container_elevation = 'md.sys.elevation.level1'
hover_state_layer_color = 'md.sys.color.on-surface'
hover_state_layer_opacity = 'md.sys.state.hover.state-layer-opacity'
pressed_container_elevation = 'md.sys.elevation.level0'
pressed_state_layer_color = 'md.sys.color.on-surface'
pressed_state_layer_opacity = 'md.sys.state.pressed.state-layer-opacity'
with_outline_disabled_outline_color = 'md.sys.color.outline'
with_outline_disabled_outline_opacity = 0.12
with_outline_focus_outline_color = 'md.sys.color.on-surface'
with_outline_hover_outline_color = 'md.sys.color.outline'
with_outline_outline_color = 'md.sys.color.outline'
with_outline_outline_width = '1 DIPS'
with_outline_pressed_outline_color = 'md.sys.color.outline'
