"""Design tokens for md.comp.progress-indicator."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

active_indicator_track_space = 4
active_indicator_color = 'md.sys.color.primary'
active_indicator_shape = 'md.sys.shape.corner.full'
active_indicator_thickness = 4
stop_indicator_color = 'md.sys.color.primary'
stop_indicator_shape = 4
stop_indicator_size = 4
track_color = 'md.sys.color.secondary-container'
track_shape = 'md.sys.shape.corner.full'
track_thickness = 4
