"""Design tokens for md.ref.typeface."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

brand = 'Roboto'
plain = 'Roboto'
weight_bold = 700
weight_medium = 500
weight_regular = 400
