"""Design tokens for md.sys.shape."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

corner_extra_large = 'SHAPE_FAMILY_ROUNDED_CORNERS'
corner_extra_large_top = 'SHAPE_FAMILY_ROUNDED_CORNERS'
corner_extra_small = 'SHAPE_FAMILY_ROUNDED_CORNERS'
corner_extra_small_top = 'SHAPE_FAMILY_ROUNDED_CORNERS'
corner_full = 'SHAPE_FAMILY_CIRCULAR'
corner_large = 'SHAPE_FAMILY_ROUNDED_CORNERS'
corner_large_end = 'SHAPE_FAMILY_ROUNDED_CORNERS'
corner_large_start = 'SHAPE_FAMILY_ROUNDED_CORNERS'
corner_large_top = 'SHAPE_FAMILY_ROUNDED_CORNERS'
corner_medium = 'SHAPE_FAMILY_ROUNDED_CORNERS'
corner_none = 'SHAPE_FAMILY_ROUNDED_CORNERS'
corner_small = 'SHAPE_FAMILY_ROUNDED_CORNERS'
