"""Design tokens for md.sys.state."""

# Auto generated by _token_converter.py
# Do not edit this file directly.

dragged_state_layer_opacity = 0.16
focus_indicator_inner_offset = 0
focus_indicator_outer_offset = 2
focus_indicator_thickness = 3
focus_state_layer_opacity = 0.1
hover_state_layer_opacity = 0.08
pressed_state_layer_opacity = 0.1
