version: 2

build:
    os: ubuntu-lts-latest
    tools:
        nodejs: "latest"
    jobs:
        install:
            - npm install vitepress
        build:
            html:
                - npx vitepress build docs
                - mkdir -p $READTHEDOCS_OUTPUT/
                - mv docs/.vitepress/dist $READTHEDOCS_OUTPUT/html
