# Run the unit tests

name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci-tests:31-docker-container-ci-image-build-test
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      # - name: Install pip dependencies
      # run: |
      #   pip install .[dev]
      - name: Test with pytest
        run: |
          pytest -m 'not record_gif' --cov=material_ui --cov-branch --cov-report=xml
      - name: Upload coverage report artifact to Github
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
