# Run the unit tests

name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install system libraries
        run: |
          python -m pip install --upgrade pip
          sudo apt-get update
          # sudo apt-get install -y 
          sudo apt-get install -y libegl1 xvfb libxkbcommon-x11-0
      - name: Install pip dependencies
        run: |
          pip install .[dev]
      - name: Test with pytest
        run: |
          xvfb-run --auto-servernum pytest --cov=material_ui --cov-branch --cov-report=xml
      - name: Upload coverage report artifact to Github
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
